export const FETCH_ALL_BOOKS_REQUESTED = 'FETCH_ALL_BOOKS_REQUESTED';
export const FETCH_ALL_BOOKS_SUCCEEDED = 'FETCH_ALL_BOOKS_SUCCEEDED';
export const FETCH_ALL_BOOKS_FAILED = 'FETCH_ALL_BOOKS_FAILED';